name: Update public events data

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-events:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true # Needed to push the commit below
          token: ${{ secrets.WEBSITE_UPDATE_TOKEN }} # token by openrail-tech user

      - name: Setup required build tools with mise
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5

      - name: Fetch and convert ICS calendar to JSON
        run: mise run events-fetch

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "chore(events): update public events data"
          commit_user_name: "OpenRail Tech"
          commit_user_email: "techadmin@openrailassociation.org"
          commit_author: "OpenRail Tech <techadmin@openrailassociation.org>"
          file_pattern: data/events_public.json
